name: realzookeeper
description: An easy to use RealZoo save editor!
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1

flutter:
  uses-material-design: true